"""create todos table

Revision ID: 368a38931a3f
Revises: 4571363afc4f
Create Date: 2026-03-03 00:53:01.897473

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "368a38931a3f"
down_revision: str | Sequence[str] | None = "4571363afc4f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
