"""Verifica que los modelos SQLAlchemy y las migraciones Alembic no tengan drift.

Equivale a `alembic check`: si un modelo declara algo que ninguna migración crea
(o al revés), este test falla. Es exactamente la red que habría cazado O1
(`todos.due_date` sin migración) antes de llegar a producción. Gate duro permanente.
"""

from alembic import command
from alembic.config import Config
from sqlalchemy.engine import Engine


# Tipo de test: Integration
def test_models_match_migrations_no_drift(_postgres_engine: Engine) -> None:
    """No debe haber diferencias entre los modelos y el esquema migrado a head."""
    # _postgres_engine ya aplicó `alembic upgrade head` y dejó DATABASE_URL apuntando
    # al contenedor; command.check compara los modelos contra ese esquema real y
    # lanza AutogenerateDiffsDetected si hay drift.
    command.check(Config("alembic.ini"))
