"""Scalar API Reference mount for FastAPI.

Replaces the default Swagger UI at /docs. Reads the OpenAPI schema generated by
FastAPI (via app.openapi_url) — no coupling to domain/application/infrastructure.

Activation is controlled by the SCALAR_DOCS_ENABLED env var (default: enabled).
"""

from __future__ import annotations

import os
from typing import Final

from fastapi import FastAPI
from fastapi.responses import HTMLResponse
from scalar_fastapi import Layout, Theme, get_scalar_api_reference

# Scalar's proxy avoids CORS issues when the bundle (loaded from jsdelivr) needs
# to fetch the OpenAPI schema from this API. Without it, the browser blocks
# cross-origin reads of /openapi.json since the API's CORS only allows
# localhost:3000 by default.
_SCALAR_PROXY_URL: Final[str] = "https://proxy.scalar.com"
_DEFAULT_THEME: Final[Theme] = Theme.KEPLER
_DEFAULT_LAYOUT: Final[Layout] = Layout.MODERN
_ENV_FLAG: Final[str] = "SCALAR_DOCS_ENABLED"


def is_scalar_docs_enabled() -> bool:
    """Return True if the SCALAR_DOCS_ENABLED env var is truthy (default: enabled)."""
    return os.getenv(_ENV_FLAG, "true").strip().lower() == "true"


def setup_scalar_docs(
    app: FastAPI,
    *,
    title: str,
    theme: Theme = _DEFAULT_THEME,
    layout: Layout = _DEFAULT_LAYOUT,
) -> bool:
    """Mount Scalar UI at /docs if enabled by env.

    Returns True if the endpoint was registered, False if disabled.
    Idempotent at the FastAPI app level: re-registering the same path would 409.
    The API description lives in the OpenAPI schema at /openapi.json, which Scalar
    renders alongside the title.
    """
    if not is_scalar_docs_enabled():
        return False

    openapi_url = app.openapi_url or "/openapi.json"

    @app.get("/docs", include_in_schema=False)
    async def scalar_docs() -> HTMLResponse:
        return get_scalar_api_reference(
            openapi_url=openapi_url,
            title=title,
            scalar_proxy_url=_SCALAR_PROXY_URL,
            theme=theme,
            dark_mode=True,
            layout=layout,
            persist_auth=True,
        )

    return True
