from app.features.todos.domain.entities.todo import Todo
from app.features.todos.infrastructure.models.todo_model import TodoModel


def map_todo_model_to_entity(todo_model: TodoModel) -> Todo:
    """Map ORM todo model to domain entity."""
    return Todo(
        id=todo_model.id,
        user_id=todo_model.user_id,
        title=todo_model.title,
        description=todo_model.description,
        is_completed=todo_model.is_completed,
        due_date=todo_model.due_date,
        created_at=todo_model.created_at,
        updated_at=todo_model.updated_at,
    )


def map_new_todo_entity_to_model(todo: Todo, *, todo_id: str) -> TodoModel:
    """Build a new ORM todo model from a freshly created domain entity.

    The identity is generated by the repository (persistence concern) and injected
    here, because a new entity still has `id is None`.
    """
    return TodoModel(
        id=todo_id,
        user_id=todo.user_id,
        title=todo.title,
        description=todo.description,
        is_completed=todo.is_completed,
        due_date=todo.due_date,
    )


def map_todo_entity_to_model(todo_model: TodoModel, todo: Todo) -> TodoModel:
    """Apply mutable domain todo state into an existing ORM todo model."""
    todo_model.title = todo.title
    todo_model.description = todo.description
    todo_model.is_completed = todo.is_completed
    todo_model.due_date = todo.due_date
    return todo_model
